package com.banking.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Represents a bank account in the banking application system.
 * 
 * This class encapsulates all account-related information including account details,
 * balance, status, and type. Each account is associated with a user and supports
 * various banking operations like deposits, withdrawals, and transfers.
 * 
 * @author Banking App Team
 * @version 1.0
 */
public class Account {
    /** Unique identifier for the account */
    private long id;
    
    /** Unique account number (generated by the system) */
    private String accountNumber;
    
    /** Foreign key referencing the user who owns this account */
    private long userId;
    
    /** Type of account (SAVINGS or CURRENT) */
    private AccountType accountType;
    
    /** Current balance of the account */
    private BigDecimal balance;
    
    /** Current status of the account (ACTIVE or INACTIVE) */
    private AccountStatus status;
    
    /** Timestamp when the account was created */
    private LocalDateTime createdAt;

    /**
     * Enumeration of supported account types.
     */
    public enum AccountType {
        /** Savings account with interest-bearing capabilities */
        SAVINGS, 
        
        /** Current/checking account for daily transactions */
        CURRENT
    }

    /**
     * Enumeration of account statuses.
     */
    public enum AccountStatus{
        /** Account is active and can perform transactions */
        ACTIVE, 
        
        /** Account is inactive and cannot perform transactions */
        INACTIVE
    }

    /**
     * Default constructor for creating a new Account instance.
     * Required for frameworks like JPA/Hibernate.
     */
    public Account(){}

    /**
     * Constructs a new Account with all fields including ID.
     * Typically used when retrieving account data from the database.
     * 
     * @param id Unique account identifier
     * @param accountNumber Unique account number
     * @param userId ID of the account owner
     * @param accountType Type of account (SAVINGS or CURRENT)
     * @param balance Current account balance
     * @param status Current account status
     * @param createdAt Account creation timestamp
     */
    public Account(long id, String accountNumber, long userId, AccountType accountType, BigDecimal balance, AccountStatus status, LocalDateTime createdAt) {
        this.id = id;
        this.accountNumber = accountNumber;
        this.userId = userId;
        this.accountType = accountType;
        this.balance = balance;
        this.status = status;
        this.createdAt = createdAt;
    }

    /**
     * Constructs a new Account for creation purposes.
     * Sets default values for balance (ZERO) and status (ACTIVE).
     * ID and creation timestamp are typically set by the database.
     * 
     * @param accountNumber Unique account number
     * @param userId ID of the account owner
     * @param accountType Type of account (SAVINGS or CURRENT)
     * @param balance Initial account balance
     * @param status Initial account status
     */
    public Account(String accountNumber, long userId, AccountType accountType, BigDecimal balance, AccountStatus status) {
        this.accountNumber = accountNumber;
        this.userId = userId;
        this.accountType = accountType;
        this.balance = BigDecimal.ZERO;
        this.status = AccountStatus.ACTIVE;
    }

    /**
     * Returns the unique identifier of the account.
     * 
     * @return the account ID
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the unique identifier for the account.
     * Typically used by the database layer when persisting the account.
     * 
     * @param id the account ID to set
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the unique account number.
     * 
     * @return the account number
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the unique account number.
     * 
     * @param accountNumber the account number to set
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Returns the ID of the user who owns this account.
     * 
     * @return the user ID
     */
    public long getUserId() {
        return userId;
    }

    /**
     * Sets the ID of the user who owns this account.
     * 
     * @param userId the user ID to set
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * Returns the current balance of the account.
     * 
     * @return the account balance
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * Sets the balance of the account.
     * Should be used carefully as it directly modifies the account balance.
     * 
     * @param balance the balance to set
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * Returns the type of the account.
     * 
     * @return the account type
     */
    public AccountType getAccountType() {
        return accountType;
    }

    /**
     * Sets the type of the account.
     * 
     * @param accountType the account type to set
     */
    public void setAccountType(AccountType accountType) {
        this.accountType = accountType;
    }

    /**
     * Returns the timestamp when the account was created.
     * 
     * @return the account creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the timestamp when the account was created.
     * Typically set by the database layer when the account is first created.
     * 
     * @param createdAt the creation timestamp to set
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Returns the current status of the account.
     * 
     * @return the account status
     */
    public AccountStatus getStatus() {
        return status;
    }

    /**
     * Sets the status of the account.
     * 
     * @param status the account status to set
     */
    public void setStatus(AccountStatus status) {
        this.status = status;
    }

    /**
     * Returns a string representation of the Account object.
     * 
     * @return string representation of the account
     */
    @Override
    public String toString() {
        return "Account{" +
                "id=" + id +
                ", accountNumber='" + accountNumber + '\'' +
                ", userId=" + userId +
                ", accountType=" + accountType +
                ", balance=" + balance +
                ", status=" + status +
                ", createdAt=" + createdAt +
                '}';
    }
}
